In [1]:
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt
%matplotlib notebook
import csv
import os
import itertools
from sklearn.decomposition import PCA

In [2]:
from scripts.utility import *
from scripts.features import *
from scripts.decomposer import hierarchical_decomposition

# Features
It is a good idea to save our features in text files, so that we only have to calculate them once. Later on when we employ clustering, we can just read the values off of these files instead of iterating over the graphs again, which is time consuming.

## 1. Geometrical

### 1.1 Number of nodes and edges

In [17]:
# Calculate the number of nodes and edges for each network and save them to files
with open('features/n_nodes.txt', 'w') as node_file, open('features/n_edges.txt', 'w') as edge_file:
    for network_id, G in graph_generator():
        node_file.write(network_id + '\t' + str(nx.number_of_nodes(G)) + '\n') # nx.number_of_nodes() function
        edge_file.write(network_id + '\t' + str(nx.number_of_edges(G)) + '\n') # use tab character \t, not two spaces
        
###NOTE: Have to pull features from github before running script
##IDEA: Can calculate every feature on the same loop

Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnecte

### 1.2 Average node degree

In [12]:
# Calculate the average node degree, i.e. the average number of edges that are connected to a node,
# for each network and write them to a file
with open('features/average_node_degree.txt', 'w') as file:
    for network_id, G in graph_generator(): # check this access to graph_generator
        average_node_degree = np.mean(list(G.degree().values()))
        file.write(network_id + '\t' + str(average_node_degree) + '\n')

Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnected parts
Removing disconnecte

### 1.3 Vein density

Vein density **$\sigma$** is calculated by summing the total length of all veins and dividing by total leaf area.


In [ ]:
save_feature(vein_density, skip_existing=True, clean=False)

### 1.4 Areole area

Areole area **$A$** is obtained calculating basic cycle areas using the standard formula for the area of a general polygon.

In [ ]:
save_feature(areole_area, skip_existing=True, clean=False)

### 1.5 Areole density 

Areole density **$\rho_A$** is the total number of areoles divided by leaf area.

In [ ]:
save_feature(areole_density, skip_existing=True, clean=False)

### 1.6 Weighted vein thickness

Weighted vein thickness **$d$** is calculated as the total sum of the product radius*length of each
    individual vein segment divided by total vein length

In [ ]:
save_feature(weighted_vein_thickness, skip_existing=True, clean=False)

## 2. Topological

### 2.1 Nesting number

In [ ]:
save_feature(nesting_numbers, skip_existing=True, clean=True)

In [18]:
#%%capture 
print('alan')

alan


# Data Analysis

In [15]:
generator = graph_generator()

In [16]:
_, G = next(generator)

Removing disconnected parts


In [ ]:
H = clean_graph(G)

In [ ]:
pos = nx.get_node_attributes(G, 'pos')
nx.draw(G, pos=pos, node_size=0.01)

#basis = nx.cycle_basis(G)
#subgraph_nodes = list(itertools.chain(*basis[:700])) # TODO: how to generate connected subgraphs?
#H = clean_graph(G.subgraph(subgraph_nodes))
#pos = nx.get_node_attributes(H,'pos')
#nx.draw(H, pos=pos, node_size=0.0001)

In [ ]:
nesting_number, nesting_number_no_ext = nesting_numbers(H)
print(nesting_number)
print(nesting_number_no_ext)

In [ ]:
_, G = get_graph_from_data()

### Principal Component Analysis

In [3]:
X = np.array([[-1, -1, 2, 2,], [-2, -1, -2, -1], [-3, -2, 3, 3], [1, 1, 2, 2], [2, 1, 4, 4], [3, 2, -1, -1]])
pca = PCA(n_components=4)
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components=4, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [4]:
print('Input Vector\n',X)

Input Vector
 [[-1 -1  2  2]
 [-2 -1 -2 -1]
 [-3 -2  3  3]
 [ 1  1  2  2]
 [ 2  1  4  4]
 [ 3  2 -1 -1]]


In [12]:
print('Fit\n',pca.fit(X)) 

Fit
 PCA(copy=True, iterated_power='auto', n_components=4, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)


In [14]:
print('Orthogonal Eigenvectors: Principal components \n',pca.components_)  #Eigenvectors on the Feature space:  PC1
                                                                                      #PC2
                                                                                      #PC3

Orthogonal Eigenvectors: Principal components 
 [[ 0.2216594   0.19488984 -0.70829235 -0.64125424]
 [-0.81015898 -0.5065792  -0.24722735 -0.16093034]
 [ 0.44312427 -0.72989863  0.31378374 -0.41524527]
 [ 0.31328966 -0.41550385 -0.58201405  0.62487262]]


In [7]:
print('Eigenvalues: Explained variance\n', pca.explained_variance_) #Amount of variance explained by each of the selected components.

Eigenvalues: Explained variance
 [ 8.26868369  6.47630428  0.03753452  0.02303306]


In [11]:
print('Normalized eigenvalues: Variance ratio\n', pca.explained_variance_ratio_) #Percentage of variance explained by each of the selected components.

Normalized eigenvalues: Variance ratio
 [ 0.5584852   0.43742393  0.00253516  0.0015557 ]


In [10]:
print('PCA transform: Projected data into PCA subspace\n',pca.transform(X))   #X is projected on the first principal components previously extracted from a training set.

PCA transform: Projected data into PCA subspace
 [[-1.20937127  1.07145479  0.28834089  0.02664113]
 [ 3.32590146  3.35331416 -0.16418253  0.16678979]
 [-3.19712651  2.79019427  0.03052945 -0.14157578]
 [-0.37627277 -1.56202159 -0.28520784 -0.17778724]
 [-2.85370656 -3.18849593 -0.04500663  0.22121957]
 [ 4.31057566 -2.46444571  0.17552666 -0.09528747]]
